plugins:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "storage/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ["describe", "context", "feature", "scenario", "let"]

Style/AsciiComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
